### ISSUE TITLE
Error - y = 0!

### ISSUE THREAD

**Issue by TopoR1** [Tombez/algae#1]
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at cachedText (https://tombez.github.io/algae/src/js/graphics.js:237:7)
    at Module.draw (https://tombez.github.io/algae/src/js/graphics.js:49:5)
    at loop (https://tombez.github.io/algae/src/js/index.js:234:11)

The error is caused if you temporarily leave the tab and return to it.

Also, the problem with the Q button, it does not turn off!

Please fix!

**Comment by Tombez** [comment]
I'm looking into the Exception.
What server are you using that the Q button doesn't work?
Controlling minions on https://github.com/m-byte918/MultiOgarII is working for me.

**Comment by TopoR1** [comment]
Server: SuperOP

**Comment by TopoR1** [comment]
And so, it works.

**Comment by Tombez** [comment]
Thank you for creating this issue. I believe I have fixed the uncaught DOMException, feel free to test the new commit and re-open this issue if it persists.

As for the Q button, I was able to reproduce using the SuperOP server, but not other servers with this client. Which leads me to believe that bug is caused by the SuperOP server.
